# Generated by Django 3.2.18 on 2024-08-30 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_url', models.CharField(max_length=90)),
                ('module_name', models.CharField(choices=[('Students', 'Students'), ('Reports', 'Reports'), ('Academic', 'Academic'), ('Settings', 'Settings'), ('Users', 'Users')], max_length=50)),
                ('module_order', models.IntegerField(default=0)),
                ('menu_order', models.IntegerField(default=0)),
                ('menu_icon', models.CharField(blank=True, max_length=50)),
                ('background_color', models.CharField(blank=True, max_length=30)),
                ('font_color', models.CharField(blank=True, max_length=30)),
                ('is_dashboard', models.BooleanField(default=False)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu List',
                'db_table': 'menu_list',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=65)),
                ('last_name', models.CharField(blank=True, max_length=65)),
                ('full_name', models.CharField(blank=True, max_length=130)),
                ('email', models.CharField(max_length=130, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('mobile2', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=60)),
                ('photo', models.FileField(blank=True, upload_to='images/user_progile')),
                ('username', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Registration',
                'verbose_name_plural': 'User Registration List',
                'db_table': 'user_list',
            },
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_action', models.BooleanField(default=0)),
                ('insert_action', models.BooleanField(default=0)),
                ('update_action', models.BooleanField(default=0)),
                ('delete_action', models.BooleanField(default=0)),
                ('permission_date', models.DateTimeField(auto_now_add=True)),
                ('permitted_by', models.BigIntegerField(default=0)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('insert_by', models.IntegerField(default=0)),
                ('update_by', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts_app.menulist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts_app.userregistration')),
            ],
            options={
                'verbose_name': 'Access Control',
                'verbose_name_plural': 'User Access Control',
                'db_table': 'user_access_control',
            },
        ),
        migrations.AddField(
            model_name='menulist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts_app.userregistration'),
        ),
    ]
