# Generated by Django 3.2.18 on 2024-11-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('chart_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'chart_of_accounts',
            },
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=32, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('rank', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class List',
                'verbose_name_plural': 'ClassList',
                'db_table': 'class_list',
            },
        ),
        migrations.CreateModel(
            name='FinancialHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('head_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Financial Head',
                'verbose_name_plural': 'Financial Heads',
                'db_table': 'financial_head',
            },
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_url', models.CharField(max_length=90)),
                ('module_name', models.CharField(choices=[('Students', 'Students'), ('Reports', 'Reports'), ('Academic', 'Academic'), ('Settings', 'Settings'), ('Users', 'Users')], max_length=50)),
                ('module_order', models.IntegerField(default=0)),
                ('menu_order', models.IntegerField(default=0)),
                ('menu_icon', models.CharField(blank=True, max_length=50)),
                ('background_color', models.CharField(blank=True, max_length=30)),
                ('font_color', models.CharField(blank=True, max_length=30)),
                ('is_dashboard', models.BooleanField(default=False)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu List',
                'db_table': 'menu_list',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=65)),
                ('last_name', models.CharField(blank=True, max_length=65)),
                ('full_name', models.CharField(blank=True, max_length=130)),
                ('email', models.CharField(max_length=130, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('mobile2', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to='user_progile')),
                ('username', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Registration',
                'verbose_name_plural': 'User Registration List',
                'db_table': 'user_list',
            },
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_action', models.BooleanField(default=0)),
                ('insert_action', models.BooleanField(default=0)),
                ('update_action', models.BooleanField(default=0)),
                ('delete_action', models.BooleanField(default=0)),
                ('permission_date', models.DateTimeField(auto_now_add=True)),
                ('permitted_by', models.BigIntegerField(default=0)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('insert_by', models.IntegerField(default=0)),
                ('update_by', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts_app.menulist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts_app.userregistration')),
            ],
            options={
                'verbose_name': 'Access Control',
                'verbose_name_plural': 'User Access Control',
                'db_table': 'user_access_control',
            },
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('roll', models.CharField(max_length=50, unique=True)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.classlist')),
            ],
            options={
                'db_table': 'student_list',
            },
        ),
        migrations.AddField(
            model_name='menulist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts_app.userregistration'),
        ),
        migrations.CreateModel(
            name='ClassWiseFeeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.classlist')),
                ('fees_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.chartofaccounts')),
            ],
            options={
                'verbose_name_plural': 'Class Wise Fee Setup',
                'db_table': 'class_wise_fee_setup',
            },
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='financial_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.financialhead'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together={('text_id', 'financial_head')},
        ),
    ]
