# Generated by Django 3.2.18 on 2024-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_progile'),
        ),
    ]
