# Generated by Django 3.2.18 on 2024-11-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32)),
                ('fee_amount', models.FloatField(default=0)),
                ('due_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('insert_by', models.IntegerField(default=0)),
                ('update_by', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=0)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.classlist')),
                ('class_wise_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.classwisefeesetup')),
                ('fees_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Student Fee Collection',
                'db_table': 'student_fee_collection',
            },
        ),
    ]
