# Generated by Django 3.2.18 on 2024-11-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_studentfeecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeecollection',
            name='student_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.studentlist'),
            preserve_default=False,
        ),
    ]
