# Generated by Django 3.2.18 on 2024-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20240929_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('head_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Head',
                'verbose_name_plural': 'Financial Heads',
                'db_table': 'financial_head',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('chart_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('financial_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.financialhead')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'chart_of_accounts',
                'unique_together': {('text_id', 'financial_head')},
            },
        ),
    ]
