# Generated by Django 3.2.18 on 2024-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_chartofaccounts_financialhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialhead',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
