# Generated by Django 3.2.18 on 2024-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_auto_20240929_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialhead',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
