# Generated by Django 3.2.18 on 2024-10-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_auto_20240929_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWiseFeeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.classlist')),
                ('fees_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.chartofaccounts')),
            ],
            options={
                'verbose_name_plural': 'Class Wise Fee Setup',
                'db_table': 'class_wise_fee_setup',
            },
        ),
    ]
